---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Update the apt-cache, if necessary
      ansible.builtin.apt:
        cache_valid_time: 86400
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
  roles:
    - buluma.setuptools
