---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check mozsyncserver user exists
      ansible.builtin.command:
        cmd: id mozsyncserver
      changed_when: false
