---
name: Ansible Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@ba54de22a6edeea3aa385cd8c5f20ec1f960a30b
        with:
          targets: "."
          override-deps: |
            ansible==5.4.0
            ansible-lint==5.4.0
            yamllint==1.26.3
          args: ""
